name: Deploy to AKS

on:
  push:
    paths-ignore:
      - "**/az-*.yml"

jobs:
  deploy:
    runs-on: ubuntu-16.04

    # issue with 18.04 https://github.com/dotnet/core/issues/3312

    steps:
    - uses: actions/checkout@master
    
    - name: Login to Docker Hub
      uses: azure/container-actions/docker-login@master
      with:
        login-server: docker.io
        username: {{`${{ secrets.DOCKER_HUB_USERNAME }}`}}
        password: {{`${{ secrets.DOCKER_HUB_PASSWORD }}`}}
    
    - name: Build and push Docker images
      run: |
        docker-compose build
        docker-compose push

    - name: Get SQL Server connection string
      id: get-connection-string
      uses: 'docker://sixeyed/actions-sql-get-connection-string:1910'
      env:
        SQL_SERVER: {{`${{ secrets.AZURE_SQL_SERVER }}`}}        
        SQL_PASSWORD: {{`${{ secrets.AZURE_SQL_PASSWORD }}`}}

    - name: Write Kubernetes secret 
      uses: 'docker://sixeyed/actions-aks-create-secret:1910'
      env:
        AZURE_SP_NAME: {{`${{ secrets.AZURE_SP_NAME }}`}}
        AZURE_SP_TENANT: {{`${{ secrets.AZURE_SP_TENANT }}`}}
        AZURE_SP_PASSWORD: {{`${{ secrets.AZURE_SP_PASSWORD }}`}}
        AZURE_RESOURCE_GROUP: {{range .Services}}{{if eq "azure" .ID}}{{.Parameters.resourceGroup}}{{end}}{{end}}
        AKS_CLUSTER_NAME: {{range .Services}}{{if eq "aks" .ID}}{{.Parameters.clusterName}}{{end}}{{end}}
        AKS_SECRET_NAME: db-connection-string
        AKS_SECRET_FILE_NAME: file
        AKS_SECRET_FILE_VALUE: {{`${{ steps.get-connection-string.outputs.connectionString }}`}}
        
    - name: Deploy from Compose to Kubernetes
      uses: 'docker://sixeyed/actions-aks-stack-deploy:1910'          
      env:
        AZURE_SP_NAME: {{`${{ secrets.AZURE_SP_NAME }}`}}
        AZURE_SP_TENANT: {{`${{ secrets.AZURE_SP_TENANT }}`}}
        AZURE_SP_PASSWORD: {{`${{ secrets.AZURE_SP_PASSWORD }}`}}
        AZURE_RESOURCE_GROUP: {{range .Services}}{{if eq "azure" .ID}}{{.Parameters.resourceGroup}}{{end}}{{end}}
        AKS_CLUSTER_NAME: {{range .Services}}{{if eq "aks" .ID}}{{.Parameters.clusterName}}{{end}}{{end}}
        DOCKER_COMPOSE_PATH: '/github/workspace/docker-compose.production.yaml'
        DOCKER_STACK_NAME: eshoponweb